### ISSUE TITLE
ترنسمیتر h2

### ISSUE THREAD

**Issue by vm1363** [pouyaam/tls_reality_domain#1]
سلام واقعا ایده شما عالی بود واقعا حض کردم
فقط دو تا نکته
یکی اینکه تو توضیحات درج کنید که اون دامینی که برای sni استفاده میشه حتما پشت cdn کلادفلر باشه تا امکان شناسایی IP اصلی میسر نباشه (من امتحان کردم تو همه اپراتورها عالی جواب میده) الآن کلادفلیر روی sni بیشترین فیلترینگ رو انجام میده.
و لطفاً بگید که از ساب دامین استفاده کنن چون بیشتر ملت از دامین اصلی استفاده میکنن و وقتی دامین sni  فیلتر میشه باید دوباره دامین بخرن در حالی که ساب رو به راحتی میشه عوض کرد

**Comment by pouyaam** [comment]
سلام
ممنون بات پیشنهاداتون حتما اعمال میشه

درمورد h2 من الان تست کردم کار میکنه بدون تغییر

اگر ممکنه دقیق تر بگید ممنون میشم

**Comment by vm1363** [comment]
شما درست می فرمایید ایراد از اینترنت من بود کار نمی کرد
باز هم ممنون از توجهتون
به امید روزی که ماهم بتونیم بدون دغدغه از اینترنت استفاده کنیم

**Comment by vm1363** [comment]
روی h2 پینگ نصف میشه ولی من دفعه اول امتحان کردم کار نکرد فکر کردم ایراد از nginx هستش
ولی بعدا مشکل رو حل کردم
اشتباهی عنوان موند h2
